name: web UI automation workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0


  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v2.1.0

    - name: setup gradlew
      run: chmod +x gradlew

    - name: Execute test
      run: ./gradlew test

    - name: Upload Cucumber Report
      uses: actions/upload-artifact@v4
      with:
        name: cucumber-report
        path: build/cucumber-reports 

    - name: Upload Web Automation Test Report
      uses: actions/upload-artifact@v4
      with:
        name: web-automation-report
        path: build/reports/tests/test

    - name: Execute UI tests
      run: ./gradlew clean test   

    - name: Upload Cucumber HTML
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ui-cucumber-report
        path: "build/cucumber-report/**"
    
    - name: Upload Cucumber JSON/XML
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ui-cucumber-json-xml
        path: |
          build/cucumber-report/cucumber.json
          build/cucumber-report/cucumber.xml
    
    - name: Cara membuka report
      if: always()
      run: |
        echo "Download **ui-cucumber-report**, unzip, lalu buka **index.html**" >> $GITHUB_STEP_SUMMARY

